baseURL = 'https://www.poloxue.com/backtrader'
languageCode = 'zh-cn'
title = 'Backtrader 中文'

#  information on 'doc' type pages.
enableGitInfo = true

disableKinds = ['taxonomy']

[modules]
[[module.imports]]
  path = 'github.com/alex-shpak/hugo-book'

[params]
  BookTheme = 'dark'
  BookToC = true
  BookLogo = 'logo.png'
  BookSection = 'docs'
  BookRepo = 'https://github.com/poloxue/docs.backtrader'
  BookCommitPath = 'commit'
  BookEditPath = 'blob/master'
  BookDateFormat = 'Jan 2, 2006'
  BookSearch = true
  BookComments = true
  BookPortableLinks = true
  BookServiceWorker = true

[markup]
  defaultMarkdownHandler = "goldmark"
	
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
